<div class="section">
	<a name="top"></a>
	<div class="title">
		<h1 class="info">
			Edit campaign: <?php echo $this->campaign->title ?>
		</h1>
	</div>
	<div class="left">
		<?php echo $this->form ?>
		<div class="clear"></div>
	</div>
	<div class="right">
		<?php echo $this->action( "workers-status", "campaign", "marketing", array( "id" => $this->campaign->id_campaign ) ); ?>
		<a href="<?php echo $this->url( array
		(
			"controller" => "campaign",
			"action"	 => "workers-start",
			"module"	 => "marketing",
			"id" 		 => $this->campaign->id_campaign
		) )?>">Start workers</a>
	</div>
</div>