<div class="section">
	<a name="top"></a>
	<div class="title">
		<h1 class="info">
			Starting campaign: '<?php echo $this->campaign->title ?>' workers
		</h1>
	</div>
	<div class="left">
		<?php if( count( $this->errors ) ) : ?>
			<ul>
			<?php foreach( $this->errors as $k => $e ) : ?>
				<li><strong><?php echo $e ?></strong></li>
				<li><pre><?php echo $this->outputs[$k] ?></pre></li>
			<?php endforeach; ?>
			</ul>
		<?php endif; ?>
	</div>
</div>